#![allow(dead_code)]

//! Generates phpMyAdmin `config.inc.php` files for per-site and global setups.

use std::path::PathBuf;

#[derive(Debug, Clone, PartialEq)]
pub struct PmaServerConfig {
    pub host: String,
    pub port: u16,
    pub user: String,
    pub password: String,
    /// When `Some(name)`, restrict the user to a single DB (`only_db`).
    /// When `None`, all accessible databases are exposed.
    pub db_name: Option<String>,
}

/// Central location of per-site config.inc.php files.
pub fn site_config_path(site_name: &str) -> PathBuf {
    let base = dirs::home_dir().unwrap_or_else(|| PathBuf::from("."));
    base.join(".config")
        .join("valet-manager")
        .join("phpmyadmin")
        .join(format!("{site_name}.config.inc.php"))
}

pub fn global_config_path() -> PathBuf {
    let base = dirs::home_dir().unwrap_or_else(|| PathBuf::from("."));
    base.join(".config")
        .join("valet-manager")
        .join("phpmyadmin")
        .join("global.config.inc.php")
}

/// Generate a 48-character hex secret (24 random bytes) suitable for
/// `$cfg['blowfish_secret']`. NEVER log or persist outside of AppConfig.
pub fn generate_blowfish_secret() -> String {
    let bytes: [u8; 24] = rand::random();
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

/// Render a per-site phpMyAdmin `config.inc.php`.
///
/// When `server.db_name` is `Some(name)`, the file pins phpMyAdmin to a single
/// database via `$cfg['Servers'][$i]['only_db']`. When `None`, every database
/// the configured MySQL user can see is exposed.
pub fn render_site_config(blowfish_secret: &str, server: &PmaServerConfig) -> String {
    let mut out = String::new();
    out.push_str("<?php\n");
    out.push_str("// Generated by Valet Manager — do not edit manually\n");
    out.push_str("declare(strict_types=1);\n\n");
    out.push_str(&format!(
        "$cfg['blowfish_secret'] = '{}';\n\n",
        escape_php_single_quoted(blowfish_secret),
    ));
    out.push_str("$i = 0;\n");
    out.push_str("$i++;\n");
    out.push_str("$cfg['Servers'][$i]['auth_type']        = 'cookie';\n");
    out.push_str(&format!(
        "$cfg['Servers'][$i]['host']             = '{}';\n",
        escape_php_single_quoted(&server.host),
    ));
    out.push_str(&format!(
        "$cfg['Servers'][$i]['port']             = {};\n",
        server.port,
    ));
    out.push_str("$cfg['Servers'][$i]['compress']         = false;\n");
    out.push_str("$cfg['Servers'][$i]['AllowNoPassword']  = false;\n");
    out.push_str(&format!(
        "$cfg['Servers'][$i]['user']             = '{}';\n",
        escape_php_single_quoted(&server.user),
    ));
    out.push_str(&format!(
        "$cfg['Servers'][$i]['password']         = '{}';\n",
        escape_php_single_quoted(&server.password),
    ));
    match &server.db_name {
        Some(name) => {
            out.push_str(&format!(
                "$cfg['Servers'][$i]['only_db']          = '{}';\n",
                escape_php_single_quoted(name),
            ));
        }
        None => {
            out.push_str("// All databases accessible to the configured user\n");
        }
    }
    out.push('\n');
    out.push_str("$cfg['UploadDir']        = '';\n");
    out.push_str("$cfg['SaveDir']          = '';\n");
    out.push_str("$cfg['SendErrorReports'] = 'never';\n");
    out
}

/// Render a global phpMyAdmin config that lists every database the configured
/// MySQL user can access. No `only_db` is set.
pub fn render_global_config(blowfish_secret: &str, server: &PmaServerConfig) -> String {
    let mut all_dbs = server.clone();
    all_dbs.db_name = None;
    render_site_config(blowfish_secret, &all_dbs)
}

/// Write a config.inc.php with 0640 permissions.
pub async fn write_site_config(site_name: &str, content: &str) -> anyhow::Result<PathBuf> {
    let path = site_config_path(site_name);
    if let Some(parent) = path.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }
    tokio::fs::write(&path, content).await?;
    apply_secure_permissions(&path)?;
    Ok(path)
}

pub async fn remove_site_config(site_name: &str) -> anyhow::Result<()> {
    let path = site_config_path(site_name);
    if tokio::fs::try_exists(&path).await.unwrap_or(false) {
        tokio::fs::remove_file(&path).await?;
    }
    Ok(())
}

/// Apply 0640 permissions on Unix; no-op on other platforms.
pub fn apply_secure_permissions(path: &std::path::Path) -> anyhow::Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(path)?.permissions();
        perms.set_mode(0o640);
        std::fs::set_permissions(path, perms)?;
    }
    let _ = path;
    Ok(())
}

fn escape_php_single_quoted(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_server(db: Option<&str>) -> PmaServerConfig {
        PmaServerConfig {
            host: "127.0.0.1".into(),
            port: 3306,
            user: "appuser".into(),
            password: "s3cret".into(),
            db_name: db.map(|s| s.to_string()),
        }
    }

    #[test]
    fn blowfish_secret_is_48_hex_chars() {
        let s = generate_blowfish_secret();
        assert_eq!(s.len(), 48);
        assert!(s.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn two_blowfish_secrets_differ() {
        let a = generate_blowfish_secret();
        let b = generate_blowfish_secret();
        assert_ne!(a, b, "secrets must be random");
    }

    #[test]
    fn render_site_config_site_only_includes_only_db() {
        let s = render_site_config("deadbeef", &sample_server(Some("myapp_db")));
        assert!(s.contains("$cfg['Servers'][$i]['only_db']          = 'myapp_db';"));
        assert!(s.contains("$cfg['Servers'][$i]['auth_type']        = 'cookie';"));
        assert!(s.contains("$cfg['Servers'][$i]['user']             = 'appuser';"));
        assert!(s.contains("$cfg['Servers'][$i]['password']         = 's3cret';"));
    }

    #[test]
    fn render_site_config_all_dbs_omits_only_db() {
        let s = render_site_config("deadbeef", &sample_server(None));
        assert!(!s.contains("only_db"));
        assert!(s.contains("// All databases accessible"));
    }

    #[test]
    fn render_site_config_includes_blowfish_secret() {
        let s = render_site_config("deadbeef", &sample_server(None));
        assert!(s.contains("$cfg['blowfish_secret'] = 'deadbeef';"));
    }

    #[test]
    fn render_site_config_emits_required_keys() {
        let s = render_site_config("xx", &sample_server(Some("db")));
        for key in [
            "$cfg['Servers'][$i]['host']",
            "$cfg['Servers'][$i]['port']",
            "$cfg['Servers'][$i]['compress']",
            "$cfg['Servers'][$i]['AllowNoPassword']",
            "$cfg['UploadDir']",
            "$cfg['SaveDir']",
            "$cfg['SendErrorReports']",
        ] {
            assert!(s.contains(key), "missing {key}");
        }
    }

    #[test]
    fn render_global_config_never_has_only_db() {
        let s = render_global_config("xx", &sample_server(Some("mydb")));
        assert!(!s.contains("only_db"));
    }

    #[test]
    fn escapes_single_quotes_and_backslashes() {
        let server = PmaServerConfig {
            host: "127.0.0.1".into(),
            port: 3306,
            user: "us'er".into(),
            password: "a\\b'c".into(),
            db_name: None,
        };
        let s = render_site_config("xx", &server);
        assert!(s.contains(r"us\'er"));
        assert!(s.contains(r"a\\b\'c"));
    }

    #[test]
    fn site_config_path_under_valet_manager() {
        let p = site_config_path("foo");
        let s = p.to_string_lossy();
        assert!(s.contains("valet-manager"));
        assert!(s.contains("phpmyadmin"));
        assert!(s.ends_with("foo.config.inc.php"));
    }

    #[test]
    fn global_config_path_under_valet_manager() {
        let s = global_config_path().to_string_lossy().to_string();
        assert!(s.contains("phpmyadmin"));
        assert!(s.ends_with("global.config.inc.php"));
    }

    #[tokio::test]
    async fn write_site_config_is_0640() {
        let tmp = std::env::temp_dir().join(format!(
            "vm-pma-perm-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
        ));
        std::env::set_var("HOME", &tmp);
        let path = write_site_config("permsite", "<?php // x\n").await.unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o640, "expected 0640, got {:o}", mode);
        }
        let _ = std::fs::remove_dir_all(&tmp);
        let _ = path;
    }

    #[tokio::test]
    async fn remove_site_config_is_idempotent() {
        let tmp = std::env::temp_dir().join(format!(
            "vm-pma-rm-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
        ));
        std::env::set_var("HOME", &tmp);
        // Removing a nonexistent config must succeed.
        assert!(remove_site_config("ghost").await.is_ok());
        // Write then remove.
        let _ = write_site_config("real", "<?php // x\n").await.unwrap();
        assert!(remove_site_config("real").await.is_ok());
        assert!(remove_site_config("real").await.is_ok()); // double-remove
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
